### ISSUE TITLE
where is %<+% come from, thanks.

### ISSUE THREAD

**Issue by liamxg** [JorgensenD/SARSCOV2_tree#2]
> mcc_col_tree_plot("./mcc.nex", "2020-03-29", "country_dict.txt", internal = "Reykjavik", style = 3)
Error in btr %<+% tipdata : could not find function "%<+%"

**Comment by JorgensenD** [comment]
It is from the ggtree package from Guangchuang Yu, I will add to the top of the document.
https://github.com/YuLab-SMU/ggtree

**Comment by liamxg** [comment]
thanks.
